/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class study_F */

#ifndef _Included_study_F
#define _Included_study_F
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     study_F
 * Method:    NativeHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_study_F_NativeHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
